import type { DebateMessage, DebateMeta } from './types'

interface PdfExportOptions {
  topic: string
  messages: DebateMessage[]
  meta: DebateMeta | null
  style: 'minimal' | 'detailed'
}

function escapeHtml(text: string): string {
  const div = document.createElement('div')
  div.textContent = text
  return div.innerHTML
}

function formatDate(): string {
  return new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 50)
}

function buildMinimalHtml(data: PdfExportOptions): string {
  const { topic, messages, meta } = data
  const date = formatDate()
  const rounds = meta?.rounds ?? '?'
  const model = meta?.model ?? 'Unknown'

  const roundsMap = new Map<number | string, DebateMessage[]>()
  const judgeMessages: DebateMessage[] = []

  for (const msg of messages) {
    if (msg.isJudge) {
      judgeMessages.push(msg)
    } else {
      const key = msg.round
      if (!roundsMap.has(key)) roundsMap.set(key, [])
      roundsMap.get(key)!.push(msg)
    }
  }

  const sortedRoundKeys = Array.from(roundsMap.keys()).sort((a, b) => {
    if (typeof a === 'number' && typeof b === 'number') return a - b
    return String(a).localeCompare(String(b))
  })

  let roundSections = ''
  for (const roundKey of sortedRoundKeys) {
    const msgs = roundsMap.get(roundKey)!
    roundSections += `
      <div style="margin-bottom:24px;">
        <h2 style="font-size:16px; color:#555; border-bottom:1px solid #ddd; padding-bottom:6px; margin-bottom:12px;">
          Round ${roundKey}
        </h2>
        ${msgs
          .map(
            (m) => `
          <div style="margin-bottom:14px;">
            <div style="font-weight:bold; color:${m.color}; margin-bottom:4px;">
              ${escapeHtml(m.agent)}
              ${m.side ? `<span style="color:#888; font-weight:normal;"> — ${escapeHtml(m.side)}</span>` : ''}
            </div>
            <div style="color:#666; font-size:12px; margin-bottom:4px;">${escapeHtml(m.role)}</div>
            <div style="white-space:pre-wrap; line-height:1.5;">${escapeHtml(m.message)}</div>
          </div>
        `
          )
          .join('')}
      </div>
    `
  }

  let judgeSection = ''
  if (judgeMessages.length > 0) {
    judgeSection = `
      <div style="margin-top:32px; border-top:2px solid #333; padding-top:20px;">
        <h2 style="font-size:18px; color:#333; margin-bottom:16px;">Judge Verdict</h2>
        ${judgeMessages
          .map(
            (m) => `
          <div style="margin-bottom:14px;">
            <div style="font-weight:bold; color:${m.color}; margin-bottom:4px;">${escapeHtml(m.agent)}</div>
            <div style="white-space:pre-wrap; line-height:1.5;">${escapeHtml(m.message)}</div>
          </div>
        `
          )
          .join('')}
      </div>
    `
  }

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8" />
      <style>
        body {
          font-family: Georgia, 'Times New Roman', serif;
          margin: 40px;
          color: #222;
          line-height: 1.6;
        }
        h1 { font-size: 24px; margin-bottom: 4px; }
      </style>
    </head>
    <body>
      <h1>${escapeHtml(topic)}</h1>
      <div style="color:#888; font-size:13px; margin-bottom:24px;">
        ${date} · ${escapeHtml(model)} · ${rounds} round${rounds !== 1 ? 's' : ''}
      </div>
      ${roundSections}
      ${judgeSection}
      <div style="margin-top:48px; padding-top:12px; border-top:1px solid #ddd; color:#aaa; font-size:11px; text-align:center;">
        Generated by AI Debate Arena
      </div>
    </body>
    </html>
  `
}

function buildDetailedHtml(data: PdfExportOptions): string {
  const { topic, messages, meta } = data
  const date = formatDate()
  const rounds = meta?.rounds ?? '?'
  const model = meta?.model ?? 'Unknown'

  const agentMap = new Map<string, { color: string; role: string }>()
  for (const msg of messages) {
    if (!msg.isJudge && !agentMap.has(msg.agent)) {
      agentMap.set(msg.agent, { color: msg.color, role: msg.role })
    }
  }

  const agentChips = Array.from(agentMap.entries())
    .map(
      ([name, { color }]) => `
      <span style="display:inline-flex;align-items:center;margin:0 6px 6px 0;padding:4px 12px;border-radius:16px;background:${color}18;color:${color};font-size:13px;font-weight:600;border:1px solid ${color}40;">
        <span style="width:8px;height:8px;border-radius:50%;background:${color};margin-right:6px;"></span>
        ${escapeHtml(name)}
      </span>
    `
    )
    .join('')

  const roundsMap = new Map<number | string, DebateMessage[]>()
  const judgeMessages: DebateMessage[] = []

  for (const msg of messages) {
    if (msg.isJudge) {
      judgeMessages.push(msg)
    } else {
      const key = msg.round
      if (!roundsMap.has(key)) roundsMap.set(key, [])
      roundsMap.get(key)!.push(msg)
    }
  }

  const sortedRoundKeys = Array.from(roundsMap.keys()).sort((a, b) => {
    if (typeof a === 'number' && typeof b === 'number') return a - b
    return String(a).localeCompare(String(b))
  })

  let roundSections = ''
  for (const roundKey of sortedRoundKeys) {
    const msgs = roundsMap.get(roundKey)!
    roundSections += `
      <div style="margin-bottom:28px;">
        <div style="font-size:13px;font-weight:700;text-transform:uppercase;letter-spacing:1.5px;color:#6b7280;margin-bottom:16px;padding-bottom:8px;border-bottom:2px solid #e5e7eb;">
          Round ${roundKey}
        </div>
        ${msgs
          .map(
            (m) => `
          <div style="display:flex;gap:12px;margin-bottom:16px;">
            <div style="flex-shrink:0;width:40px;height:40px;border-radius:50%;background:${m.color}20;color:${m.color};display:flex;align-items:center;justify-content:center;font-weight:700;font-size:16px;border:2px solid ${m.color};">
              ${escapeHtml(m.agent.charAt(0).toUpperCase())}
            </div>
            <div style="flex:1;background:#f9fafb;border-radius:10px;padding:14px 16px;border-left:4px solid ${m.color};">
              <div style="display:flex;align-items:center;gap:8px;margin-bottom:6px;">
                <span style="font-weight:700;color:${m.color};font-size:15px;">${escapeHtml(m.agent)}</span>
                <span style="font-size:11px;color:#fff;background:#6b7280;padding:2px 8px;border-radius:10px;">${escapeHtml(m.role)}</span>
                ${m.side ? `<span style="font-size:11px;color:#9ca3af;font-style:italic;">(${escapeHtml(m.side)})</span>` : ''}
              </div>
              <div style="white-space:pre-wrap;line-height:1.6;color:#374151;font-size:14px;">${escapeHtml(m.message)}</div>
            </div>
          </div>
        `
          )
          .join('')}
      </div>
    `
  }

  let judgeSection = ''
  if (judgeMessages.length > 0) {
    judgeSection = `
      <div style="margin-top:28px;background:#fffbeb;border:1px solid #f59e0b;border-radius:10px;padding:20px;">
        <div style="font-size:18px;font-weight:700;color:#92400e;margin-bottom:14px;display:flex;align-items:center;gap:8px;">
          <span style="font-size:22px;">&#9878;</span> Judge Verdict
        </div>
        ${judgeMessages
          .map(
            (m) => `
          <div style="margin-bottom:12px;">
            <div style="font-weight:700;color:#78350f;margin-bottom:4px;">${escapeHtml(m.agent)}</div>
            <div style="white-space:pre-wrap;line-height:1.6;color:#451a03;font-size:14px;">${escapeHtml(m.message)}</div>
          </div>
        `
          )
          .join('')}
      </div>
    `
  }

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8" />
      <style>
        body {
          font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
          margin: 0;
          color: #1f2937;
          line-height: 1.5;
        }
      </style>
    </head>
    <body>
      <div style="background:linear-gradient(135deg,#1e3a5f,#2563eb);color:#fff;padding:32px 40px;">
        <h1 style="margin:0 0 8px 0;font-size:26px;font-weight:700;">${escapeHtml(topic)}</h1>
        <div style="font-size:13px;opacity:0.85;display:flex;gap:16px;flex-wrap:wrap;">
          <span>${date}</span>
          <span>&middot;</span>
          <span>${escapeHtml(model)}</span>
          <span>&middot;</span>
          <span>${rounds} round${rounds !== 1 ? 's' : ''}</span>
        </div>
      </div>
      <div style="padding:20px 40px;background:#f3f4f6;border-bottom:1px solid #e5e7eb;">
        <div style="display:flex;flex-wrap:wrap;align-items:center;">
          ${agentChips}
        </div>
      </div>
      <div style="padding:28px 40px;">
        ${roundSections}
        ${judgeSection}
      </div>
      <div style="margin-top:24px;padding:16px 40px;border-top:1px solid #e5e7eb;color:#9ca3af;font-size:11px;text-align:center;">
        Generated by AI Debate Arena
      </div>
    </body>
    </html>
  `
}

export async function exportPdf(options: PdfExportOptions): Promise<void> {
  const { topic, style } = options

  const htmlContent = style === 'minimal' ? buildMinimalHtml(options) : buildDetailedHtml(options)

  const container = document.createElement('div')
  container.style.position = 'fixed'
  container.style.left = '-9999px'
  container.style.top = '0'
  container.style.width = '800px'
  container.innerHTML = htmlContent
  document.body.appendChild(container)

  try {
    const html2pdf = (await import('html2pdf.js')).default
    const timestamp = Date.now()
    const slug = slugify(topic)
    const filename = `debate-${slug}-${timestamp}.pdf`

    await html2pdf()
      .set({
        margin: 0,
        filename,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
      })
      .from(container)
      .save()
  } finally {
    document.body.removeChild(container)
  }
}
